### ISSUE TITLE
wsclient AllBookTickers() and AllMarketTickers() is not working

### ISSUE THREAD

**Issue by neo-godlike** [xenking/binance-api#2]
when i call AllBookTickers() method. i got error websocket upgrade faild. 
because the url include char “!” and its encoded. like @!bookTicker 
please check it.

**Comment by xenking** [comment]
Hello. Indeed, there is a problem. The problem is related to escaping the exclamation mark in the [xenking/fastws](https://github.com/xenking/fastws) library. fasthttp.URI converts the exclamation mark `!` to `%21` by default. To solve this problem, you need to remove escaping or abandon fasthttp.URI in the fastws library
